export const privacy = {
    es: {
        'date': 'Ultima actualización: 22/06/2024.',
        'notice': 'Aviso de privacidad',
        'description': 'Somos una empresa que brinda servicios para venta de autopartes con el fin de mejorar la experiencia de nuestros clientes, nuestro domicilio para recibir notificaciones actualmente es Jilotepec 389, ubicado en Tlalnepantla de baz en el Estado de México. Contamos con una amplia gama de productos que te brindará la comodidad y solución que buscas en el mercado, por lo que contemplamos todos los puntos que son indispensables pero no limitados por lo que están sujetos a cambios en cualquier momento para incluir mejoras o ajustes en nuestros servicios, así mismo somos responsables del manejo de sus datos personales conforme con la Ley Federal de Protección de Datos Personales en Posesión de Particulares y al capítulo VI de las prácticas responsables de la protección de datos, ponemos a su disposición nuestro Aviso de Privacidad en su versión Web, con el fin de dar a conocer el tratamiento que daremos a sus datos personales, así como el derecho que puede ejercer como titular de sus datos personales. Le recomendamos leer cuidadosamente ya que la sola disposición del presente AVISO DE PRIVACIDAD sin que usted se oponga, otorga su consentimiento tácito para permitirnos tratar sus datos personales con base en lo establecido en este escrito. Nuestra principal labor es brindarle al consumidor una solución, nos dedicamos a la compra y venta de refacciones automotrices, contamos con una amplia gama de productos que te harán la vida más cómoda, tenemos para ti nuevas formas de contacto ahora podrás encontrarnos en Whatsapp, Facebook, Instagram y en nuestra página refautomex.com. ¿Para que ocupamos tus datos personales? Lo indispensable:',
        'section': {
            'title1': 'Servicios que ofrecemos',
            'leyend1': 'Contamos con atención en sucursales y nuestro apartado web con el cual podrás encontrar lo que necesitas y pedirlo en los domicilios que aplique según nuestros parámetros para envío y herramientas disponibles en el momento, Tenemos los contactos de nuestros clientes y cuentas con las que podemos realizar pedidos y manejar con nuestro cliente los días adecuados como fechas de entrega de productos de consumidores, siempre registramos tus pedidos para darle un seguimiento personalizado: 1.- Actualmente es necesario tener una cuenta con nostros para generar un pedido en sucursal. Todo pedido es vigente por un máximo de tiempo de 6 meses, pasado este tiempo no nos hacemos responsables de ningún pedido realizado por el cliente. 2.- Nos reservamos la autorización para buscar entre nuestros resgistros con el fin de dar seguimiento a algún pedido.',
            'title2': 'Pedidos y contacto',
            'leyend2': 'Contactarte vía telefónica o por mensaje, queremos avisarte cuando tu pedido lo tengamos listo para entrega y apoyarte solucionando dudas de refacciones por medio de imágenes, números de parte o descripciones que nos ayude a brindarte el servicio que necesitas. Con la nueva funcionalidad de e-commerce que manejamos podrás realizar tus pedidos en línea y nosotros te lo llevamos hasta la puerta de tu casa si cumple con las características necesarias como cercanía a los puntos o sucursales que tenemos disponibles para tí como brindarte la mejor experiencia con cuentas de usuario y seguimiento de tus pedidos dentro de tu panel.',
            'title3': 'Facturación',
            'leyend3': 'La facturación de productos y servicios tanto como emitir notas de compras realizadas para nuestros clientes, como de servicios prestados por nosotros están optimizados para brindarte un mejor servicio y atención, en caso de que necesites una factura de tu compra, no dudes en solicitarla, nosotros te la haremos llegar en el menor tiempo posible tanto en nuestra sucursal como en nuestro portal web, nuestro proceso de facturación es el mismo para ambos casos por medio de nuestro sistema de facturación electrónica.',
            'title4': 'Envíos, Contenidos y promociones',
            'leyend4': 'Realizar análisis en las compras que los clientes realizan para mejorar nuestros servicios. Crear nuevos contenidos y lanzar promociones que satisfagan las necesidades del mercado del momento, Enviarte anuncios, promociones, novedades y descuentos de nuestros productos a usuarios que pueda interesar nuestras promociones.',
            'title5': 'Encuestas de satisfacción y buzón de sugerencias',
            'leyend5': 'Realizar encuestas o evaluaciones para que tanto proveedores como clientes nos apoyen en mejorar la experiencia al consumidor, así como tener un buzón de sugerencias para que nos ayudes a mejorar.',
            'title6': 'Promociones de temporada',
            'leyend6': 'Publicar promociones de temporada, informarte de lo nuevo del momento y de las promociones que tenemos para ti, así como de los productos que están en tendencia.',
            'title7': 'Publicidad y redes sociales',
            'leyend7': 'Incluir nuestras redes sociales para tener un mejor trato con el cliente, generaciones de tu cuenta con nosotros, así como la publicidad de nuestros productos y servicios, proveedores o empresas con las que trabajamos y contamos para brindarte un mejor servicio.',
            'title8': 'Cuentas Refautomex',
            'leyend8': 'Para uso de nuestro servicio de e-commerce será necesario tener una cuenta Refautomex con los datos actualizados antes de cada compra el envío adecuado de productos, así como el seguimiento de tus pedidos será a través del panel web de cada cliente, el usuario tendrá la opcion de poder llenar los datos de facturación desde su cuenta para una mejor experiencia de compra. Todas las tablas, información y datos personales serán almacenados, nosotros no guardamos contraseñas por lo que pedimos que no se comparta con nadie contraseñas, datos bancarios ni otro tipo de dato sensible que merezca su debido cuidado y manejo para los fines que son utilizados.'
        }
    },
    en: {
        'date': 'Last update: 06/22/2024.',
        'notice': 'Privacy Notice',
        'description': 'We are a company that provides services for the sale of auto parts in order to improve the experience of our customers, our address for receiving notifications is currently Jilotepec 389, located in Tlalnepantla de baz in the State of Mexico. We have a wide range of products that will provide you with the comfort and solution you are looking for in the market, so we contemplate all the points that are essential but not limited to, so they are subject to changes at any time to include improvements or adjustments in our services, we are also responsible for the handling of your personal data in accordance with the Federal Law on Protection of Personal Data Held by Private Parties and Chapter VI of the responsible data protection practices, we make available our Privacy Notice in its Web version, in order to inform you of the treatment we will give to your personal data, as well as the rights you can exercise as the owner of your personal data. We recommend you to read carefully since the mere provision of this PRIVACY NOTICE without you objecting, gives your tacit consent to allow us to process your personal data based on what is established in this document. Our main task is to provide the consumer with a solution, we are dedicated to the purchase and sale of automotive parts, we have a wide range of products that will make your life more comfortable, we have new ways of contact now you can find us on Whatsapp, Facebook, Instagram and on our page refautomex.com. Why do we use your personal data? The essential:',
        'section': {
            'title1': 'Services we offer',
            'leyend1': 'We have attention in branches and our web section with which you can find what you need and order it at the addresses that apply according to our parameters for shipping and tools available at the time, We have the contacts of our customers and accounts with which we can place orders and manage with our client the appropriate days such as consumer product delivery dates, we always register your orders to give you personalized follow-up: 1.- Currently it is necessary to have an account with us to generate an order in the branch. All orders are valid for a maximum of 6 months, after this time we are not responsible for any order placed by the customer. 2.- We reserve the authorization to search among our records in order to follow up on an order.',
            'title2': 'Orders and contact',
            'leyend2': 'Contact you by phone or message, we want to notify you when your order is ready for delivery and support you solving doubts about parts through images, part numbers or descriptions that help us provide the service you need. With the new e-commerce functionality that we handle you can place your orders online and we will take it to your door if it meets the necessary characteristics such as proximity to the points or branches that we have available for you as well as provide you with the best experience with user accounts and tracking of your orders within your panel.',
            'title3': 'Billing',
            'leyend3': 'The billing of products and services as well as issuing purchase notes made for our customers, as well as services provided by us are optimized to provide you with better service and attention, in case you need an invoice for your purchase, do not hesitate to request it, we will send it to you in the shortest possible time both in our branch and on our website, our billing process is the same for both cases through our electronic billing system.',
            'title4': 'Shipments, Contents and promotions',
            'leyend4': 'Analyze the purchases that customers make to improve our services. Create new content and launch promotions that meet the needs of the current market, Send you ads, promotions, news and discounts of our products to users who may be interested in our promotions.',
            'title5': 'Satisfaction surveys and suggestion box',
            'leyend5': 'Conduct surveys or evaluations so that both suppliers and customers help us improve the consumer experience, as well as have a suggestion box to help us improve.',
            'title6': 'Seasonal promotions',
            'leyend6': 'Publish seasonal promotions, inform you about the latest trends and the promotions we have for you, as well as the products that are trending.',
            'title7': 'Advertising and social networks',
            'leyend7': 'Include our social networks to have a better treatment with the client, generations of your account with us, as well as the advertising of our products and services, suppliers or companies with which we work and count on to provide you with a better service.',
            'title8': 'Refautomex Accounts',
            'leyend8': 'For the use of our e-commerce service it will be necessary to have a Refautomex account with updated data before each purchase the appropriate shipment of products, as well as the tracking of your orders will be through the web panel of each client, the user will have the option to be able to fill in the billing data from their account for a better shopping experience. All tables, information and personal data will be stored, we do not save passwords so we ask that passwords, bank details or any other type of sensitive data that deserves due care and handling for the purposes for which they are used are not shared.'
        }
    }
}